name: Public IP
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        uses: haythem/public-ip@v1.2
        if: success() || failure()
        id: ip
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
